name: Terraform

on:
  # push:
  #   branches:
  #     - main
  release:
    types: [published]
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: modules/web-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="db_pass_1=${{ secrets.DB_PASSWORD }}" -var="db_pass_2=${{ secrets.DB_PASSWORD }}" -out=tfplan

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: terraform apply -auto-approve tfplan

    #   - name: Terraform Destroy
    #     id: destroy
    #     run: terraform destroy -auto-approve -var="db_pass_1=${{ secrets.DB_PASSWORD }}" -var="db_pass_2=${{ secrets.DB_PASSWORD }}"
